- name: HOMEBREW_CASK_OPTS設定
  shell: export HOMEBREW_CASK_OPTS="--appdir=/Applications"

#- name: homebrew-caskインストール
#  homebrew: name=brew-cask state=latest

- name: caskパッケージインストール
  homebrew_cask: name={{ item.name }} state={{ item.state | default('installed') }}
  with_items: "{{homebrew_cask_packages}}"
  register: cask_result

